
services:
  redis:
    image: 'redislabs/redismod'
    ports:
      - '6379:6379'

  web1:
    build:
      context: ./web
    image: ${DOCKERHUB_USERNAME}/web1:latest
    restart: on-failure
    hostname: web1
    expose: 
      - '5000'
    ports:
      - '81:5000'

  web2:
    build:
      context: ./web
    image: ${DOCKERHUB_USERNAME}/web2:latest
    restart: on-failure
    hostname: web2
    expose: 
      - '5000'
    ports:
      - '82:5000'

  nginx:
    build:
      context: ./nginx
    image: ${DOCKERHUB_USERNAME}/nginx:latest
    ports:
      - '80:80'
    depends_on:
      - web1
      - web2



