name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'docker-compose.yaml'
      - 'web/**'
      - 'nginx/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set DockerHub username in .env
      run: echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" > .env

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
    - name: Push the Images into the repo
      run: docker buildx build -t "${{secrets.DOCKERHUB_USERNAME}}"/web1:latest ./web
           docker buildx build -t "${{secrets.DOCKERHUB_USERNAME}}"/web2:latest ./web
           docker buildx build -t "${{secrets.DOCKERHUB_USERNAME}}"/nginx:latest ./nginx
           docker push "${{secrets.DOCKERHUB_USERNAME}}"/web1:latest
           docker push "${{secrets.DOCKERHUB_USERNAME}}"/web1:latest
           docker push "${{secrets.DOCKERHUB_USERNAME}}"/web1:latest


    # - name: Generate self-signed certs
    #   run: |
    #     mkdir -p nginx/certs
    #     if [ ! -f nginx/certs/server.crt ]; then
    #     openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    #     -keyout nginx/certs/server.key \
    #     -out nginx/certs/server.crt \
    #     -subj "/CN=localhost"
    #     fi

    - name: Build all services with Compose file
      run: docker compose build

    - name: Push all images to Docker Hub
      run: docker compose push

